export const TOPIC_POOLS: Record<string, string[]> = {
  General: ['Why do we keep souvenirs?', 'What makes a room feel calm?', 'Why do we hum when we work?', 'Why do queues form even when there is space?', 'What is the oldest thing you own?', 'Why do we whisper in quiet places?', 'What makes a coincidence feel like fate?', 'Why do we smile at babies?', 'What makes a house feel like home?', 'Why do we keep ticket stubs?', 'Why do yawns spread?', 'What makes a stranger feel familiar?', 'Why do we talk to pets?', 'Why do we love rain on windows?'],
  Everyday: ['Who invented the sandwich?', 'Why is coffee the default morning ritual?', 'Where does the weekend go?', 'What makes comfort food comforting?', 'Why do we take the long way home?', 'How did the weekend become two days?', 'Why do elevators have mirrors?', 'Why do we say "cheese" for photos?', 'Who decided Monday starts the week?', 'Why do we knock on doors twice?', 'What happened to handwritten letters?', 'Why wear watches when phones exist?', 'Why do we say "sleep tight"?', 'How did pockets get so small?'],
  Nature: ['How do birds know when to leave?', 'Why is the sea salty?', 'How do trees talk underground?', 'Where do butterflies winter?', 'How does moss choose its side?', 'Why do leaves change color?', 'How do rivers pick their path?', 'Why do clouds float when they weigh tons?', 'How do seeds know which way is up?', 'Why does rain smell so good?', 'How do bees agree on a new home?', 'Why do pine trees stay green?', 'Why does dew form in patterns?', 'How do forests heal after fire?'],
  Objects: ['Who decided the shape of a fork?', 'Why do clocks go clockwise?', 'How did the mirror change us?', 'Why is paper still here?', 'Why are keys still metal?', 'What is the story of the umbrella?', 'Who invented the zipper?', 'Why are manhole covers round?', 'How did the chair win over sitting on floors?', 'Why do pencils sometimes lack erasers?', 'What made glass everywhere?', 'Why are buttons sided differently?', 'Who chose the QWERTY layout?', 'Why did suitcases get wheels so late?'],
  People: ['Why do we blush?', 'How did handshakes start?', 'Why do strangers help strangers?', 'How do accents form?', 'Why do we keep old letters?', 'What makes someone good with names?', 'Why do we laugh when it hurts?', 'How did names get their meanings?', 'Why do we miss places we have never been?', 'What makes a voice comforting?', 'Why do we trust some faces instantly?', 'How do habits spread between friends?', 'Why do we applaud?', 'What makes a good listener?'],
  Food: ['Why is bread the oldest food?', 'How did tea conquer the world?', 'Why do we eat cake at celebrations?', 'What makes chocolate feel like love?', 'Why is breakfast different everywhere?', 'How did spices start wars?', 'Why do we dip things?', 'Why do we crave salt?', 'How did ice cream become a summer thing?', 'Why do recipes say "a pinch"?', "What makes grandma's food taste better?", 'Why do we toast bread?', 'How did pizza travel the world?', 'Why do we clink glasses?'],
  Words: ['Where do idioms come from?', 'Why do we say "OK"?', 'How do new words get born?', 'Why do some words feel soft?', 'What is the oldest word still used?', 'Why do languages borrow words?', 'How did "goodbye" evolve?', 'Why do we have nicknames?', 'What makes a word funny?', 'How do slang words spread?', 'Why do we swear when we hurt?', 'What words did Shakespeare invent?', 'Why does "robot" come from a play?', 'How do emojis change meaning?'],
  History: ['What did the printing press change quietly?', 'Which ideas spread faster than armies?', 'What will this decade be remembered for?', 'How did maps change minds?', 'Why did we build monuments?', 'What did the bicycle change for women?', 'How did salt shape empires?', 'Why did we stop wearing hats?', 'What did the elevator make possible?', 'How did coffee houses spark revolutions?', 'Why did we start measuring time?', 'What did libraries mean to ancient cities?', 'How did the postal service change love?', 'Why did we domesticate dogs first?'],
  Tech: ['How does the internet find anything?', 'Why do we still use passwords?', 'What makes a video go viral?', 'How do screens make color?', 'Why did the mouse win?', 'What happens when you press a key?', 'How do phones know where you are?', 'Why do we scroll infinitely?', 'What makes code elegant?', 'How did the camera change memory?', 'Why do we trust machines with secrets?', 'What did the calculator change in school?', 'How do games feel so good?', 'Why is the cloud just computers?'],
  Art: ['Why do we love sunsets in paintings?', 'What makes a melody stick?', 'How did blue become a favorite color?', 'Why do we dance?', 'What makes a photo art?', 'How did comics learn to move?', 'Why do museums feel quiet?', 'What makes a story timeless?', 'How did pottery survive everything?', 'Why do we doodle?', 'What makes a building beautiful?', 'How did music get its scales?', 'Why do we frame things?', 'What makes a good villain?'],
  Space: ['Why is the night sky dark?', 'How does the moon steady the earth?', 'What would rain be like on Mars?', 'Why do planets have rings?', 'How far is the nearest star, really?', 'Why do comets have tails?', 'What is space made of between things?', 'How does gravity bend time?', 'Why do we look for water on other worlds?', 'What would a day on Venus feel like?', 'How did the moon get there?', 'Why do astronauts exercise?', 'What makes a planet a planet?', 'How do we hear the universe?'],
  Animals: ['Why do cats purr?', 'How do dogs read our faces?', 'Why do birds sing at dawn?', 'How do ants decide together?', 'Why do whales sing so far?', 'How do cats always land upright?', 'Why do fireflies glow in sync?', 'How do spiders choose a spot?', 'Why do elephants remember?', 'How do crows recognize faces?', 'Why do otters hold hands?', 'How do bees dance directions?', 'Why do sloths move slowly?', 'How do fish sleep in currents?'],
};

export const DEEP_POOLS: Record<string, string[]> = {
  Society: ['Why do civilizations collapse?', 'What makes a society trust itself?', 'Why does inequality keep returning?', 'What is the price of convenience?', 'How do norms quietly control us?', 'What makes a law feel fair?', 'Why do crowds behave differently?', 'How does power corrupt, exactly?', 'What does a healthy society optimize for?', 'Why do we obey strangers in uniforms?'],
  Mind: ['Why do we dream?', 'Is attention the same as thought?', 'Why does time feel faster as we age?', 'What is the self, exactly?', 'Why do we forget on purpose?', 'How do emotions decide for us?', 'Why do we crave certainty?', 'What is intuition really?', 'Why do we get used to everything?', 'Can we think without words?'],
  Time: ['How will we be wrong in the future?', 'What is progress, really?', 'Why do we plan as if we live forever?', 'What deserves to be remembered?', 'How do small choices compound?', 'What era are we actually living in?', 'Why does nostalgia feel warm and sad?', 'What will historians miss about us?', 'How fast is now?', 'Why do deadlines exist?'],
  Meaning: ['What makes work feel meaningful?', 'Why do we create when nothing asks us to?', 'What makes a good life good?', 'Why does beauty move us?', 'What do we owe each other?', 'How do we know when enough is enough?', 'Why do we seek stories?', 'What survives after us?', 'What is a quiet life worth?', 'Why keep old letters?'],
  Science: ['Why is the universe comprehensible?', 'What is nothing, really?', 'How did life begin from chemistry?', 'Why do physical laws seem fine-tuned?', 'What is information, physically?', 'How does order emerge from chaos?', 'Why is math unreasonably useful?', 'What limits what we can know?', 'Is randomness real?', 'How does complexity grow?'],
  Ethics: ['When is lying kind?', 'What do we owe the future?', 'Is it wrong to waste potential?', 'Why judge outcomes over intentions?', 'What makes an action good?', 'Do we deserve our talents?', 'When should we interfere?', 'What is fair, exactly?', 'Why is doing right hard?', 'Can machines be responsible?'],
  Love: ['Why do we love who we love?', 'What makes friendship last?', 'How does grief prove love?', 'Why is vulnerability scary and necessary?', 'What does home mean in a person?', 'Why fear being truly known?', 'How do we love what we cannot keep?', 'What makes trust rebuildable?', 'Why does kindness ripple?', 'What is the difference between needing and loving?'],
  You: ['What are you avoiding right now?', 'When did you last change your mind?', 'What would you do if no one watched?', 'Which of your beliefs are borrowed?', 'What are you quietly proud of?', 'What fear is worth keeping?', 'What would you teach your younger self?', 'What does your anger protect?', 'What small thing sustains you?', 'Who are you becoming?'],
};
