export const TOPIC_POOLS: Record<string, string[]> = {
  General: ['Why do we keep souvenirs?', 'What makes a room feel calm?', 'Why do we hum when we work?', 'Why do queues form even when there is space?', 'What is the oldest thing you own?', 'Why do we whisper in quiet places?', 'What makes a coincidence feel like fate?', 'Why do we smile at babies?', 'What makes a house feel like home?', 'Why do we keep ticket stubs?', 'Why do yawns spread?', 'What makes a stranger feel familiar?', 'Why do we talk to pets?', 'Why do we love rain on windows?'],
  Everyday: ['Who invented the sandwich?', 'Why is coffee the default morning ritual?', 'Where does the weekend go?', 'What makes comfort food comforting?', 'Why do we take the long way home?', 'How did the weekend become two days?', 'Why do elevators have mirrors?', 'Why do we say "cheese" for photos?', 'Who decided Monday starts the week?', 'Why do we knock on doors twice?', 'What happened to handwritten letters?', 'Why wear watches when phones exist?', 'Why do we say "sleep tight"?', 'How did pockets get so small?'],
  Nature: ['How do birds know when to leave?', 'Why is the sea salty?', 'How do trees talk underground?', 'Where do butterflies winter?', 'How does moss choose its side?', 'Why do leaves change color?', 'How do rivers pick their path?', 'Why do clouds float when they weigh tons?', 'How do seeds know which way is up?', 'Why does rain smell so good?', 'How do bees agree on a new home?', 'Why do pine trees stay green?', 'Why does dew form in patterns?', 'How do forests heal after fire?'],
  Objects: ['Who decided the shape of a fork?', 'Why do clocks go clockwise?', 'How did the mirror change us?', 'Why is paper still here?', 'Why are keys still metal?', 'What is the story of the umbrella?', 'Who invented the zipper?', 'Why are manhole covers round?', 'How did the chair win over sitting on floors?', 'Why do pencils sometimes lack erasers?', 'What made glass everywhere?', 'Why are buttons sided differently?', 'Who chose the QWERTY layout?', 'Why did suitcases get wheels so late?'],
  People: ['Why do we blush?', 'How did handshakes start?', 'Why do strangers help strangers?', 'How do accents form?', 'Why do we keep old letters?', 'What makes someone good with names?', 'Why do we laugh when it hurts?', 'How did names get their meanings?', 'Why do we miss places we have never been?', 'What makes a voice comforting?', 'Why do we trust some faces instantly?', 'How do habits spread between friends?', 'Why do we applaud?', 'What makes a good listener?'],
  Food: ['Why is bread the oldest food?', 'How did tea conquer the world?', 'Why do we eat cake at celebrations?', 'What makes chocolate feel like love?', 'Why is breakfast different everywhere?', 'How did spices start wars?', 'Why do we dip things?', 'Why do we crave salt?', 'How did ice cream become a summer thing?', 'Why do recipes say "a pinch"?', "What makes grandma's food taste better?", 'Why do we toast bread?', 'How did pizza travel the world?', 'Why do we clink glasses?'],
  Words: ['Where do idioms come from?', 'Why do we say "OK"?', 'How do new words get born?', 'Why do some words feel soft?', 'What is the oldest word still used?', 'Why do languages borrow words?', 'How did "goodbye" evolve?', 'Why do we have nicknames?', 'What makes a word funny?', 'How do slang words spread?', 'Why do we swear when we hurt?', 'What words did Shakespeare invent?', 'Why does "robot" come from a play?', 'How do emojis change meaning?'],
  History: ['What did the printing press change quietly?', 'Which ideas spread faster than armies?', 'What will this decade be remembered for?', 'How did maps change minds?', 'Why did we build monuments?', 'What did the bicycle change for women?', 'How did salt shape empires?', 'Why did we stop wearing hats?', 'What did the elevator make possible?', 'How did coffee houses spark revolutions?', 'Why did we start measuring time?', 'What did libraries mean to ancient cities?', 'How did the postal service change love?', 'Why did we domesticate dogs first?'],
  Tech: ['How does the internet find anything?', 'Why do we still use passwords?', 'What makes a video go viral?', 'How do screens make color?', 'Why did the mouse win?', 'What happens when you press a key?', 'How do phones know where you are?', 'Why do we scroll infinitely?', 'What makes code elegant?', 'How did the camera change memory?', 'Why do we trust machines with secrets?', 'What did the calculator change in school?', 'How do games feel so good?', 'Why is the cloud just computers?'],
  Art: ['Why do we love sunsets in paintings?', 'What makes a melody stick?', 'How did blue become a favorite color?', 'Why do we dance?', 'What makes a photo art?', 'How did comics learn to move?', 'Why do museums feel quiet?', 'What makes a story timeless?', 'How did pottery survive everything?', 'Why do we doodle?', 'What makes a building beautiful?', 'How did music get its scales?', 'Why do we frame things?', 'What makes a good villain?'],
  Space: ['Why is the night sky dark?', 'How does the moon steady the earth?', 'What would rain be like on Mars?', 'Why do planets have rings?', 'How far is the nearest star, really?', 'Why do comets have tails?', 'What is space made of between things?', 'How does gravity bend time?', 'Why do we look for water on other worlds?', 'What would a day on Venus feel like?', 'How did the moon get there?', 'Why do astronauts exercise?', 'What makes a planet a planet?', 'How do we hear the universe?'],
  Animals: ['Why do cats purr?', 'How do dogs read our faces?', 'Why do birds sing at dawn?', 'How do ants decide together?', 'Why do whales sing so far?', 'How do cats always land upright?', 'Why do fireflies glow in sync?', 'How do spiders choose a spot?', 'Why do elephants remember?', 'How do crows recognize faces?', 'Why do otters hold hands?', 'How do bees dance directions?', 'Why do sloths move slowly?', 'How do fish sleep in currents?'],
  Sounds: ['Why do some songs feel like memory?', 'How did lullabies evolve?', 'Why does silence sometimes feel loud?', 'What is the most annoying sound on earth?', 'Why do footsteps echo differently?', 'Why do certain chords feel sad?', 'What makes a voice trustworthy?', 'How do we hear in stereo?', 'Why do alarms sound the way they do?', 'Why does chalk on a board feel so wrong?'],
  Senses: ['Why does smell trigger memory?', 'How do colors feel warm or cold?', 'Why do textures matter so much?', 'What is taste, chemically?', 'Why do we squint in bright light?', 'How does touch build trust?', 'Why does cold water shock us awake?', 'What makes something feel soft?', 'How do we sense time passing?', 'Why does food taste different when we are sick?'],
  Games: ['Why do we love winning?', 'How did chess survive a thousand years?', 'Why is randomness fun?', 'What makes a game addicting?', 'Why do kids learn through play?', 'How did sports become global?', 'Why do puzzles feel good to solve?', 'What makes a game fair?', 'Why do we cheat in games we play alone?', 'How did card games cross cultures?'],
  Travel: ['Why do we collect souvenirs?', 'How did tourism begin?', 'What makes a place feel foreign?', 'Why do trains feel romantic?', 'How did maps change who traveled?', 'What is wanderlust, really?', 'Why do airports feel liminal?', 'How did passports become a thing?', 'Why do we miss places we never knew?', 'What makes a hotel feel temporary?'],
};

export const DEEP_POOLS: Record<string, string[]> = {
  Existential: [
    'Why is there something rather than nothing?',
    'Is suffering the price of being conscious?',
    'What if you had been born in another century?',
    'Is your life a story you tell yourself, or something else?',
    'What would it mean to live without regret?',
    'Does life need a meaning, or can it just be?',
    'What will matter a thousand years from now?',
    'Why does the ordinary feel strange when you notice it?',
    'Can we ever step outside our own perspective?',
    'Is wonder itself a kind of knowledge?',
    'What would a truly free person look like?',
    'Is existence itself an accident?',
  ],
  'Philosophy of Mind': [
    'Are we our memories?',
    'Could a perfect copy of you still be you?',
    'Why does anything feel like anything?',
    'Is consciousness a thing, or a process?',
    'Where does "you" end and the world begin?',
    'Can you be wrong about your own feelings?',
    'Is the self an illusion that is useful?',
    'What does it mean to truly know another person?',
    'If your brain were scanned, would that be you?',
    'Is there a difference between "you" and "your thoughts"?',
    'Why do dreams feel real while you are in them?',
    'Can two people see the exact same color the same way?',
    'Are you the same person you were ten years ago?',
  ],
  Psychology: [
    'Why do we hurt people we love?',
    'What makes trauma feel present years later?',
    'Why do we idealize the past?',
    'What is the cost of never being truly known?',
    'Why do we repeat patterns we hate?',
    'How much of who we are is shaped by early years?',
    'Why does shame feel physical?',
    'What is the difference between guilt and shame?',
    'Why do we stay in places that are not good for us?',
    'What do we fear more — being seen, or being unseen?',
    'Why is it hard to forgive yourself?',
    'What is a defense mechanism really protecting?',
    'Why do some people make us feel small?',
    'How do we know when we are lying to ourselves?',
  ],
  'Hard Science': [
    'What existed before the universe?',
    'Is consciousness a quantum phenomenon?',
    'How does matter become mind?',
    'Why does entropy always increase?',
    'What is dark matter actually made of?',
    'Are we alone, or is the universe teeming with life we cannot detect?',
    'What would a theory of everything look like?',
    'Is math discovered or invented?',
    'Why does light have a speed limit?',
    'What happens inside a black hole?',
    'Is time travel possible in principle?',
    'Why do the laws of physics look the way they do?',
    'Could life exist without carbon?',
    'Is the universe finite or infinite?',
    'How does anesthesia turn consciousness off?',
    'Why does hot water sometimes freeze faster than cold?',
    'What makes ice slippery?',
    'How does a bicycle actually stay upright?',
    'Why do mirrors flip left and right but not up and down?',
    'What is fire, exactly?',
    'Why is the sky blue but sunsets red?',
    'What is lightning made of?',
    'How do magnets actually work?',
    'Why does helium change your voice?',
  ],
  Metaphysics: [
    'Is time a real thing or just a measurement?',
    'Do numbers exist independently of us?',
    'Could there be more than one reality?',
    'Is causality real, or a habit of our minds?',
    'Does "nothing" exist, or is that a contradiction?',
    'Is space something, or the absence of something?',
    'What is a law of nature?',
    'Are there truths that can never be known?',
    'Is the universe one thing or many things?',
    'What does it mean for something to be "real"?',
    'Could everything be information?',
    'Is identity an illusion?',
    'What is the relationship between part and whole?',
  ],
  Consciousness: [
    'How does a clump of matter have inner experience?',
    'Is consciousness fundamental, or emergent?',
    'Could an AI ever feel like something to be it?',
    'Why is there a "what it is like" to be you?',
    'Is awareness the same as thought?',
    'Can consciousness be measured?',
    'Where does awareness live?',
    'Is attention a form of consciousness?',
    'What happens to awareness when we sleep?',
    'Is consciousness continuous or discrete?',
    'Can two minds truly share one experience?',
    'Why does awareness feel unified when the brain is many parts?',
  ],
  'Time and Infinity': [
    'What is "now", really?',
    'Why does the past feel fixed but the future open?',
    'Is the present moment infinitely divisible?',
    'Why does time seem to accelerate as we age?',
    'If time is a dimension, why can we only travel one way?',
    'What does eternity actually mean?',
    'Is the future already written?',
    'Can anything truly be infinite?',
    'Is time fundamental or emergent?',
    'What would an eternity of boredom be like?',
    'Does "too late" mean the same thing to everyone?',
    'Why can we remember the past but not the future?',
  ],
  'Free Will': [
    'Do we ever truly choose, or just reveal?',
    'If our brains decide before we feel we decide, are we free?',
    'What would perfect freedom even look like?',
    'Is responsibility possible without free will?',
    'Could we want to want differently than we do?',
    'What is a decision, physically?',
    'Is luck the same as destiny?',
    'If we are products of our past, what is left to choose?',
    'Does quantum randomness rescue free will?',
    'Is self-control a form of freedom, or its opposite?',
    'What would a life without choice feel like?',
  ],
  'Life and Origins': [
    'How did the very first cell appear?',
    'Why is DNA the same code in every living thing?',
    'Are viruses alive?',
    'How did eyes evolve, and how many times?',
    'Why do we sleep at all?',
    'What was the first animal to walk on land?',
    'How do birds navigate using magnetism?',
    'Why are there so many species of beetles?',
    'How do plants warn each other with chemicals?',
    'What is the oldest living thing on Earth?',
    'Did dinosaurs have feathers?',
    'How do trees grow so tall against gravity?',
    'Why is the ocean still mostly unexplored?',
    'How does a caterpillar become a butterfly, exactly?',
    'Why did life take so long to get big?',
    'What did the first forest look like?',
  ],
  Cosmos: [
    'What happened in the first second of the universe?',
    'Why is the universe expanding faster and faster?',
    'What is a neutron star made of?',
    'Could we live on a rogue planet without a star?',
    'How do we know the age of the universe?',
    'What would falling into a black hole feel like?',
    'Why do galaxies have spiral arms?',
    'Is there an edge to the universe?',
    'What are gravitational waves, and how do we hear them?',
    'How did the moon get its craters?',
    'Why do auroras dance?',
    'What is the sun made of, and how do we know?',
    'Could there be a universe made of antimatter?',
    'How far can a single photon travel?',
    'Why do all the planets sit on one flat disc?',
    'What is the Great Attractor pulling us toward?',
  ],
  'Mind and Brain Science': [
    'How do neurons make a thought?',
    'Why does the brain use so much energy?',
    'What is a memory, physically?',
    'Why do we forget most of what we experience?',
    'How does caffeine actually work?',
    'Why do we get brain freeze?',
    'What happens in the brain when we laugh?',
    'Why do we yawn?',
    'How does the brain heal after injury?',
    'What is déjà vu?',
    'Why do we get goosebumps?',
    'What is the gut-brain connection?',
    'Why does music give us chills?',
    'Why do we dream in color, or not?',
    'How does practice physically change the brain?',
    'Why does stress make the heart race?',
  ],
  'Human Nature': [
    'Are we naturally good or selfish?',
    'Why do we find beauty in things that cannot help us?',
    'Is cruelty learned, or revealed?',
    'What makes us different from other animals, really?',
    'Why do we seek status?',
    'Is love a feeling, a choice, or a habit?',
    'What is the root of envy?',
    'Why do we care what strangers think of us?',
    'Is boredom a human invention?',
    'What makes someone wise, versus intelligent?',
    'Why do we tell stories?',
    'Is hope rational?',
    'What is the point of art that no one sees?',
    'Why do we seek what we cannot have?',
  ],
};
